/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.ControllerFoodDiary;
import Controller.CtrlBB;
import Model.ModBB;
import Model.ModUser;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author mbohd
 */
public class OurApp extends javax.swing.JFrame {

    /**
     * Creates new form OurApp
     */
    ModUser u;
    ControllerFoodDiary cfd;
    CtrlBB cbb;
    LocalDateTime now;

    public LocalDateTime getNow() {
        return now;
    }

    public void setNow(LocalDateTime now) {
        this.now = now;
    }
    
    
    
    public ModUser getU() {
        return u;
    }

    public void setU(ModUser u) {
        this.u = u;
    }
    
    public OurApp(ModUser u) {
        this.u = u;
        
        initComponents();
        
        //set tanggal
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        now = LocalDateTime.now();
        tf_tanggal.setText(dtf.format(now));
        //panggil controller
        cfd = new ControllerFoodDiary(this);
        cfd.isiTable();
        cbb = new CtrlBB(this);
        cbb.isiGraph();
    }

    public OurApp() {
        u = new ModUser("u", 1);
        
        initComponents();
        
        //set tanggal
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        now = LocalDateTime.now();
        tf_tanggal.setText(dtf.format(now));
        //panggil controller
        cfd = new ControllerFoodDiary(this);
        cfd.isiTable();
        cbb = new CtrlBB(this);
        cbb.isiGraph();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_idFood = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_nmMakanan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_jenisMkn = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sp_kalori = new javax.swing.JSpinner();
        tf_tanggal = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_FoodDiary = new javax.swing.JTable();
        btn_tmbMkn = new javax.swing.JButton();
        btn_updMkn = new javax.swing.JButton();
        btn_delMkn = new javax.swing.JButton();
        btn_tgl = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbl_totalKalori = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bBGraph2 = new GUI.BBGraph();
        tf_bb = new javax.swing.JTextField();
        btn_bb = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Aplikasi Ra Guno");

        jLabel2.setText("ID");

        tf_idFood.setEditable(false);
        tf_idFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idFoodActionPerformed(evt);
            }
        });

        jLabel3.setText("Makanan");

        jLabel4.setText("Jenis");

        cb_jenisMkn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sarapan", "Makan Siang", "Makan Malam", "Cemilan" }));

        jLabel5.setText("Kalori");

        tf_tanggal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel6.setText("Tanggal");

        tbl_FoodDiary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_FoodDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_FoodDiaryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_FoodDiary);

        btn_tmbMkn.setText("Tambah");
        btn_tmbMkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tmbMknActionPerformed(evt);
            }
        });

        btn_updMkn.setText("Update");
        btn_updMkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updMknActionPerformed(evt);
            }
        });

        btn_delMkn.setText("Hapus");
        btn_delMkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delMknActionPerformed(evt);
            }
        });

        btn_tgl.setText("Cari tanggal");
        btn_tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tglActionPerformed(evt);
            }
        });

        jLabel7.setText("Total Kalori =");

        lbl_totalKalori.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_jenisMkn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nmMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_kalori, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_idFood, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_tmbMkn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_updMkn))
                    .addComponent(btn_delMkn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_totalKalori)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_tgl))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_idFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btn_tgl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_nmMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_jenisMkn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sp_kalori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tmbMkn)
                            .addComponent(btn_updMkn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delMkn)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbl_totalKalori)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Food Diary", jPanel1);

        tf_bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bbActionPerformed(evt);
            }
        });

        btn_bb.setText("Submit");
        btn_bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bbActionPerformed(evt);
            }
        });

        jLabel8.setText("Masukan berat badan hari ini");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(bBGraph2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_bb, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_bb)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bBGraph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_bb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bb)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Progress", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_idFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idFoodActionPerformed

    private void btn_tmbMknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tmbMknActionPerformed
        // TODO add your handling code here:
        cfd.insert();
        cfd.isiTable();
        cfd.reset_field();
    }//GEN-LAST:event_btn_tmbMknActionPerformed

    private void btn_tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tglActionPerformed
        // TODO add your handling code here:
        cfd.isiTable();
    }//GEN-LAST:event_btn_tglActionPerformed

    private void tbl_FoodDiaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_FoodDiaryMouseClicked
        // TODO add your handling code here:
        cfd.isi_field(tbl_FoodDiary.getSelectedRow());
    }//GEN-LAST:event_tbl_FoodDiaryMouseClicked

    private void btn_updMknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updMknActionPerformed
        // TODO add your handling code here:
        cfd.update();
        cfd.isiTable();
    }//GEN-LAST:event_btn_updMknActionPerformed

    private void btn_delMknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delMknActionPerformed
        // TODO add your handling code here:
        cfd.delete();
        cfd.isiTable();
        cfd.reset_field();
    }//GEN-LAST:event_btn_delMknActionPerformed

    private void tf_bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bbActionPerformed

    private void btn_bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bbActionPerformed
        // TODO add your handling code here:
        cbb.inputBB();
        cbb.isiGraph();
    }//GEN-LAST:event_btn_bbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OurApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OurApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OurApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OurApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OurApp().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BBGraph bBGraph2;
    private javax.swing.JButton btn_bb;
    private javax.swing.JButton btn_delMkn;
    private javax.swing.JButton btn_tgl;
    private javax.swing.JButton btn_tmbMkn;
    private javax.swing.JButton btn_updMkn;
    private javax.swing.JComboBox<String> cb_jenisMkn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_totalKalori;
    private javax.swing.JSpinner sp_kalori;
    private javax.swing.JTable tbl_FoodDiary;
    private javax.swing.JTextField tf_bb;
    private javax.swing.JTextField tf_idFood;
    private javax.swing.JTextField tf_nmMakanan;
    private javax.swing.JFormattedTextField tf_tanggal;
    // End of variables declaration//GEN-END:variables

    public JSpinner getSp_kalori() {
        return sp_kalori;
    }

    public void setSp_kalori(JSpinner sp_kalori) {
        this.sp_kalori = sp_kalori;
    }

    public JTable getTbl_FoodDiary() {
        return tbl_FoodDiary;
    }

    public void setTbl_FoodDiary(JTable tbl_FoodDiary) {
        this.tbl_FoodDiary = tbl_FoodDiary;
    }

    public JTextField getTf_idFood() {
        return tf_idFood;
    }

    public void setTf_idFood(JTextField tf_idFood) {
        this.tf_idFood = tf_idFood;
    }

    public JTextField getTf_nmMakanan() {
        return tf_nmMakanan;
    }

    public void setTf_nmMakanan(JTextField tf_nmMakanan) {
        this.tf_nmMakanan = tf_nmMakanan;
    }

    public JFormattedTextField getTf_tanggal() {
        return tf_tanggal;
    }

    public void setTf_tanggal(JFormattedTextField tf_tanggal) {
        this.tf_tanggal = tf_tanggal;
    }

    public JComboBox<String> getCb_jenisMkn() {
        return cb_jenisMkn;
    }

    public void setCb_jenisMkn(JComboBox<String> cb_jenisMkn) {
        this.cb_jenisMkn = cb_jenisMkn;
    }

    public JButton getBtn_delMkn() {
        return btn_delMkn;
    }

    public void setBtn_delMkn(JButton btn_delMkn) {
        this.btn_delMkn = btn_delMkn;
    }

    public JButton getBtn_tmbMkn() {
        return btn_tmbMkn;
    }

    public void setBtn_tmbMkn(JButton btn_tmbMkn) {
        this.btn_tmbMkn = btn_tmbMkn;
    }

    public JButton getBtn_updMkn() {
        return btn_updMkn;
    }

    public void setBtn_updMkn(JButton btn_updMkn) {
        this.btn_updMkn = btn_updMkn;
    }

    public JLabel getLbl_totalKalori() {
        return lbl_totalKalori;
    }

    public void setLbl_totalKalori(JLabel lbl_totalKalori) {
        this.lbl_totalKalori = lbl_totalKalori;
    }

    public BBGraph getbBGraph2() {
        return bBGraph2;
    }

    public void setbBGraph2(BBGraph bBGraph2) {
        this.bBGraph2 = bBGraph2;
    }

    public JTextField getTf_bb() {
        return tf_bb;
    }

    public void setTf_bb(JTextField tf_bb) {
        this.tf_bb = tf_bb;
    }

    
    
    
}
